// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iksvgfpvqusajblfoarh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrc3ZnZnB2cXVzYWpibGZvYXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MjA2MzcsImV4cCI6MjA4NjM5NjYzN30.sCoUggLES2z4IDxnHvlFAmjFJN55jIvKI-L0dsADoKY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);